package WebGen.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SContainmentLink;

public class Anchor_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    tgs.append("<Grommet.Anchor ");
    tgs.append("href='");
    tgs.append(SPropertyOperations.getString(ctx.getPrimaryInput(), PROPS.href$lk9l));
    tgs.append("' ");
    if ((SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.icon$Yjno) != null)) {
      tgs.append("icon={");
      tgs.appendNode(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.icon$Yjno));
      tgs.append("}");
    }
    tgs.append("/>");
  }

  private static final class PROPS {
    /*package*/ static final SProperty href$lk9l = MetaAdapterFactory.getProperty(0x524c482858c411cL, 0x9a4ee783c820e868L, 0x472658573095fb8dL, 0x472658573095fb8eL, "href");
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink icon$Yjno = MetaAdapterFactory.getContainmentLink(0x524c482858c411cL, 0x9a4ee783c820e868L, 0x472658573095fb8dL, 0x472658573096051bL, "icon");
  }
}
