package WebGen.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;

public class App_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    tgs.append("import React from 'react';");
    tgs.newLine();
    tgs.append("import { BrowserRouter, Routes, Route } from 'react-router-dom';");
    tgs.newLine();
    tgs.append("import * as Icons from 'grommet-icons';");
    tgs.newLine();
    tgs.append("import * as Grommet from 'grommet';");
    tgs.newLine();
    tgs.append("\n");
    tgs.append("export const App = () => {");
    tgs.newLine();

    tgs.append("}");
  }
}
