package WebGen.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class Area_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    tgs.indent();
    tgs.append("{ name: '");
    tgs.append(SPropertyOperations.getString(ctx.getPrimaryInput(), PROPS.name$M_tP));
    tgs.append("', start: [");
    tgs.append(String.valueOf(SPropertyOperations.getInteger(ctx.getPrimaryInput(), PROPS.start_c$MF$f)));
    tgs.append(", ");
    tgs.append(String.valueOf(SPropertyOperations.getInteger(ctx.getPrimaryInput(), PROPS.start_r$M_VR)));
    tgs.append("], end: [");
    tgs.append(String.valueOf(SPropertyOperations.getInteger(ctx.getPrimaryInput(), PROPS.end_c$MMAH)));
    tgs.append(", ");
    tgs.append(String.valueOf(SPropertyOperations.getInteger(ctx.getPrimaryInput(), PROPS.end_r$MGwj)));
    tgs.append("] },");
  }

  private static final class PROPS {
    /*package*/ static final SProperty name$M_tP = MetaAdapterFactory.getProperty(0x524c482858c411cL, 0x9a4ee783c820e868L, 0x1b16beb9df5c4165L, 0x1b16beb9df5c4166L, "name");
    /*package*/ static final SProperty start_c$MF$f = MetaAdapterFactory.getProperty(0x524c482858c411cL, 0x9a4ee783c820e868L, 0x1b16beb9df5c4165L, 0x1b16beb9df5c416bL, "start_c");
    /*package*/ static final SProperty start_r$M_VR = MetaAdapterFactory.getProperty(0x524c482858c411cL, 0x9a4ee783c820e868L, 0x1b16beb9df5c4165L, 0x1b16beb9df5c4168L, "start_r");
    /*package*/ static final SProperty end_c$MMAH = MetaAdapterFactory.getProperty(0x524c482858c411cL, 0x9a4ee783c820e868L, 0x1b16beb9df5c4165L, 0x1b16beb9df5c4174L, "end_c");
    /*package*/ static final SProperty end_r$MGwj = MetaAdapterFactory.getProperty(0x524c482858c411cL, 0x9a4ee783c820e868L, 0x1b16beb9df5c4165L, 0x1b16beb9df5c416fL, "end_r");
  }
}
