package WebGen.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class Clickable_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    if (!(SPropertyOperations.getString(ctx.getPrimaryInput(), PROPS.functionName$uM6c).isBlank())) {
      tgs.append(" onclick='");
      tgs.append(SPropertyOperations.getString(ctx.getPrimaryInput(), PROPS.functionName$uM6c));
      tgs.append("'");
    }
  }

  private static final class PROPS {
    /*package*/ static final SProperty functionName$uM6c = MetaAdapterFactory.getProperty(0x524c482858c411cL, 0x9a4ee783c820e868L, 0x4b0f3085b2f8d903L, 0x4b0f3085b2f8d906L, "functionName");
  }
}
