package WebGen.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class Icon_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    tgs.append("<Icons.");
    tgs.append(SPropertyOperations.getString(ctx.getPrimaryInput(), PROPS.type$lrql));
    tgs.append(" color='");
    tgs.append(SPropertyOperations.getString(ctx.getPrimaryInput(), PROPS.color$lrSn));
    tgs.append("' />");
  }

  private static final class PROPS {
    /*package*/ static final SProperty type$lrql = MetaAdapterFactory.getProperty(0x524c482858c411cL, 0x9a4ee783c820e868L, 0x472658573095fb96L, 0x472658573095fb97L, "type");
    /*package*/ static final SProperty color$lrSn = MetaAdapterFactory.getProperty(0x524c482858c411cL, 0x9a4ee783c820e868L, 0x472658573095fb96L, 0x472658573095fb99L, "color");
  }
}
