package WebGen.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class Icon_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    tgs.indent();
    tgs.append("<");
    tgs.append(String.valueOf(SPropertyOperations.getEnum(ctx.getPrimaryInput(), PROPS.icon$WI$W)));
    if (!(SPropertyOperations.getString(ctx.getPrimaryInput(), PROPS.color$2hWV).isBlank())) {
      tgs.append(" color='");
      tgs.append(SPropertyOperations.getString(ctx.getPrimaryInput(), PROPS.color$2hWV));
      tgs.append("'");
    }
    if (!(SPropertyOperations.getString(ctx.getPrimaryInput(), PROPS.size$2huT).isBlank())) {
      tgs.append(" size='");
      tgs.append(SPropertyOperations.getString(ctx.getPrimaryInput(), PROPS.size$2huT));
      tgs.append("'");
    }
    if (!(isEmptyString(SPropertyOperations.getString(ctx.getPrimaryInput(), PROPS.functionName$uM6c)))) {
      tgs.append(" onClick={() => MyScript.");
      tgs.append(SPropertyOperations.getString(ctx.getPrimaryInput(), PROPS.functionName$uM6c));
      tgs.append("()}");
    }
    if (!(isEmptyString(SPropertyOperations.getString(ctx.getPrimaryInput(), PROPS.gridArea$AIZu)))) {
      tgs.append(" gridArea='");
      tgs.append(SPropertyOperations.getString(ctx.getPrimaryInput(), PROPS.gridArea$AIZu));
      tgs.append("'");
    }
    tgs.append(" />");
    tgs.newLine();
  }
  private static boolean isEmptyString(String str) {
    return str == null || str.isEmpty();
  }

  private static final class PROPS {
    /*package*/ static final SProperty icon$WI$W = MetaAdapterFactory.getProperty(0x524c482858c411cL, 0x9a4ee783c820e868L, 0x4b0f3085b2f7dad9L, 0x4dac150aa8d2cc98L, "icon");
    /*package*/ static final SProperty color$2hWV = MetaAdapterFactory.getProperty(0x524c482858c411cL, 0x9a4ee783c820e868L, 0x4b0f3085b2f7dad9L, 0x4b0f3085b2f7dae0L, "color");
    /*package*/ static final SProperty size$2huT = MetaAdapterFactory.getProperty(0x524c482858c411cL, 0x9a4ee783c820e868L, 0x4b0f3085b2f7dad9L, 0x4b0f3085b2f7dadeL, "size");
    /*package*/ static final SProperty functionName$uM6c = MetaAdapterFactory.getProperty(0x524c482858c411cL, 0x9a4ee783c820e868L, 0x4b0f3085b2f8d903L, 0x4b0f3085b2f8d906L, "functionName");
    /*package*/ static final SProperty gridArea$AIZu = MetaAdapterFactory.getProperty(0x524c482858c411cL, 0x9a4ee783c820e868L, 0x4b0f3085b2f914c3L, 0x1b16beb9df5cc4a6L, "gridArea");
  }
}
