package WebGen.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SReferenceLink;

public class Route_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    tgs.indent();
    tgs.append("<Route index");
    if (SPropertyOperations.getBoolean(ctx.getPrimaryInput(), PROPS.isHome$NU6q)) {
      tgs.append(" index");
    } else {
      tgs.append("path=\"");
      tgs.append(SPropertyOperations.getString(ctx.getPrimaryInput(), PROPS.route$cthg));
      tgs.append("\"");
    }
    tgs.append(" element={<");
    tgs.append(SPropertyOperations.getString(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.page$dbzl), PROPS.name$MnvL));
    tgs.append(" />}/>");
    tgs.newLine();
  }

  private static final class PROPS {
    /*package*/ static final SProperty isHome$NU6q = MetaAdapterFactory.getProperty(0x524c482858c411cL, 0x9a4ee783c820e868L, 0x2f6f0a41e01ce203L, 0x2f6f0a41e01b9386L, "isHome");
    /*package*/ static final SProperty route$cthg = MetaAdapterFactory.getProperty(0x524c482858c411cL, 0x9a4ee783c820e868L, 0x2f6f0a41e01ce203L, 0x2f6f0a41e01ce40fL, "route");
    /*package*/ static final SProperty name$MnvL = MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name");
  }

  private static final class LINKS {
    /*package*/ static final SReferenceLink page$dbzl = MetaAdapterFactory.getReferenceLink(0x524c482858c411cL, 0x9a4ee783c820e868L, 0x2f6f0a41e01ce203L, 0x2f6f0a41e01cfaf0L, "page");
  }
}
