package WebGen.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class Theme_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    tgs.append("const theme = {");
    tgs.newLine();
    ctx.getBuffer().area().increaseIndent();
    tgs.indent();
    tgs.append("global: {");
    tgs.newLine();
    ctx.getBuffer().area().increaseIndent();
    tgs.indent();
    tgs.append("font: {");
    tgs.newLine();
    ctx.getBuffer().area().increaseIndent();
    tgs.indent();
    tgs.append("family: '");
    tgs.append(SPropertyOperations.getString(ctx.getPrimaryInput(), PROPS.family$GKmR));
    tgs.append("',");
    tgs.newLine();
    tgs.indent();
    tgs.append("size: '");
    tgs.append(SPropertyOperations.getString(ctx.getPrimaryInput(), PROPS.size$K2NS));
    tgs.append("',");
    tgs.newLine();
    tgs.indent();
    tgs.append("height: '");
    tgs.append(SPropertyOperations.getString(ctx.getPrimaryInput(), PROPS.height$K3wV));
    tgs.append("',");
    tgs.newLine();
    ctx.getBuffer().area().decreaseIndent();
    tgs.indent();
    tgs.append("},");
    tgs.newLine();
    ctx.getBuffer().area().decreaseIndent();
    tgs.indent();
    tgs.append("},");
    tgs.newLine();
    ctx.getBuffer().area().decreaseIndent();
    tgs.append("};");
    tgs.newLine();
  }

  private static final class PROPS {
    /*package*/ static final SProperty family$GKmR = MetaAdapterFactory.getProperty(0x524c482858c411cL, 0x9a4ee783c820e868L, 0x47265857309494aeL, 0x47265857309494b1L, "family");
    /*package*/ static final SProperty size$K2NS = MetaAdapterFactory.getProperty(0x524c482858c411cL, 0x9a4ee783c820e868L, 0x47265857309494aeL, 0x47265857309494ffL, "size");
    /*package*/ static final SProperty height$K3wV = MetaAdapterFactory.getProperty(0x524c482858c411cL, 0x9a4ee783c820e868L, 0x47265857309494aeL, 0x4726585730949502L, "height");
  }
}
