package WebGen.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_Icons extends EnumerationDescriptorBase {

  public EnumerationDescriptor_Icons() {
    super(0x524c482858c411cL, 0x9a4ee783c820e868L, 0x4b0f3085b2f7dad4L, "Icons", "r:b4f30641-7f1b-428b-b3d8-bf4ba03b50c5(WebGen.structure)/5408595028286626516");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_Like_0 = new EnumerationDescriptor.MemberDescriptor("Like", "Like", 0x4b0f3085b2f7dad5L, "r:b4f30641-7f1b-428b-b3d8-bf4ba03b50c5(WebGen.structure)/5408595028286626517");
  private final EnumerationDescriptor.MemberDescriptor myMember_Add_0 = new EnumerationDescriptor.MemberDescriptor("Add", "Add", 0x4b0f3085b2f7dad6L, "r:b4f30641-7f1b-428b-b3d8-bf4ba03b50c5(WebGen.structure)/5408595028286626518");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x524c482858c411cL, 0x9a4ee783c820e868L, 0x4b0f3085b2f7dad4L, 0x4b0f3085b2f7dad5L, 0x4b0f3085b2f7dad6L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_Like_0, myMember_Add_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "Like":
        return myMember_Like_0;
      case "Add":
        return myMember_Add_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
