package WebGen.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_Size extends EnumerationDescriptorBase {

  public EnumerationDescriptor_Size() {
    super(0x524c482858c411cL, 0x9a4ee783c820e868L, 0x1b16beb9df5c4154L, "Size", "r:b4f30641-7f1b-428b-b3d8-bf4ba03b50c5(WebGen.structure)/1951957194037281108");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_xsmall_0 = new EnumerationDescriptor.MemberDescriptor("xsmall", "xsmall", 0x1b16beb9df5c4155L, "r:b4f30641-7f1b-428b-b3d8-bf4ba03b50c5(WebGen.structure)/1951957194037281109");
  private final EnumerationDescriptor.MemberDescriptor myMember_small_0 = new EnumerationDescriptor.MemberDescriptor("small", "small", 0x1b16beb9df5c4156L, "r:b4f30641-7f1b-428b-b3d8-bf4ba03b50c5(WebGen.structure)/1951957194037281110");
  private final EnumerationDescriptor.MemberDescriptor myMember_medium_0 = new EnumerationDescriptor.MemberDescriptor("medium", "medium", 0x1b16beb9df5c4159L, "r:b4f30641-7f1b-428b-b3d8-bf4ba03b50c5(WebGen.structure)/1951957194037281113");
  private final EnumerationDescriptor.MemberDescriptor myMember_large_0 = new EnumerationDescriptor.MemberDescriptor("large", "large", 0x1b16beb9df5c415dL, "r:b4f30641-7f1b-428b-b3d8-bf4ba03b50c5(WebGen.structure)/1951957194037281117");
  private final EnumerationDescriptor.MemberDescriptor myMember_auto_0 = new EnumerationDescriptor.MemberDescriptor("auto", "auto", 0x152bf92bb43e3d70L, "r:b4f30641-7f1b-428b-b3d8-bf4ba03b50c5(WebGen.structure)/1525586864897932656");
  private final EnumerationDescriptor.MemberDescriptor myMember_none_0 = new EnumerationDescriptor.MemberDescriptor("none", "none", 0x515c6d8557857476L, "r:b4f30641-7f1b-428b-b3d8-bf4ba03b50c5(WebGen.structure)/5862681234395985014");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x524c482858c411cL, 0x9a4ee783c820e868L, 0x1b16beb9df5c4154L, 0x1b16beb9df5c4155L, 0x1b16beb9df5c4156L, 0x1b16beb9df5c4159L, 0x1b16beb9df5c415dL, 0x152bf92bb43e3d70L, 0x515c6d8557857476L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_xsmall_0, myMember_small_0, myMember_medium_0, myMember_large_0, myMember_auto_0, myMember_none_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return myMember_none_0;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "xsmall":
        return myMember_xsmall_0;
      case "small":
        return myMember_small_0;
      case "medium":
        return myMember_medium_0;
      case "large":
        return myMember_large_0;
      case "auto":
        return myMember_auto_0;
      case "none":
        return myMember_none_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
