package WebGen.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_FillValue extends EnumerationDescriptorBase {

  public EnumerationDescriptor_FillValue() {
    super(0x524c482858c411cL, 0x9a4ee783c820e868L, 0x46b3245fb72786e1L, "FillValue", "r:b4f30641-7f1b-428b-b3d8-bf4ba03b50c5(WebGen.structure)/5094455596999476961");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_vertical_0 = new EnumerationDescriptor.MemberDescriptor("vertical", "vertical", 0x46b3245fb72786e2L, "r:b4f30641-7f1b-428b-b3d8-bf4ba03b50c5(WebGen.structure)/5094455596999476962");
  private final EnumerationDescriptor.MemberDescriptor myMember_horizontal_0 = new EnumerationDescriptor.MemberDescriptor("horizontal", "horizontal", 0x46b3245fb72786e3L, "r:b4f30641-7f1b-428b-b3d8-bf4ba03b50c5(WebGen.structure)/5094455596999476963");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x524c482858c411cL, 0x9a4ee783c820e868L, 0x46b3245fb72786e1L, 0x46b3245fb72786e2L, 0x46b3245fb72786e3L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_vertical_0, myMember_horizontal_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return myMember_horizontal_0;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "vertical":
        return myMember_vertical_0;
      case "horizontal":
        return myMember_horizontal_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
