package WebGen.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int Anchor = 0;
  public static final int App = 1;
  public static final int Component = 2;
  public static final int Home = 3;
  public static final int Icon = 4;
  public static final int NavBar = 5;
  public static final int Profile = 6;
  public static final int Theme = 7;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0x524c482858c411cL, 0x9a4ee783c820e868L);
    builder.put(0x472658573095fb8dL, Anchor);
    builder.put(0x733cadfcf05c6e05L, App);
    builder.put(0x733cadfcf05c6e24L, Component);
    builder.put(0x47265857309e671aL, Home);
    builder.put(0x472658573095fb96L, Icon);
    builder.put(0x733cadfcf05b23b8L, NavBar);
    builder.put(0x472658573099f5f5L, Profile);
    builder.put(0x47265857309494aeL, Theme);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
