package WebGen.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import jetbrains.mps.smodel.runtime.DataTypeDescriptor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptApp = createDescriptorForApp();
  /*package*/ final ConceptDescriptor myConceptButton = createDescriptorForButton();
  /*package*/ final ConceptDescriptor myConceptClickable = createDescriptorForClickable();
  /*package*/ final ConceptDescriptor myConceptConfiguration = createDescriptorForConfiguration();
  /*package*/ final ConceptDescriptor myConceptGrid = createDescriptorForGrid();
  /*package*/ final ConceptDescriptor myConceptIcon = createDescriptorForIcon();
  /*package*/ final ConceptDescriptor myConceptNavBar = createDescriptorForNavBar();
  /*package*/ final ConceptDescriptor myConceptPage = createDescriptorForPage();
  /*package*/ final ConceptDescriptor myConceptRoute = createDescriptorForRoute();
  /*package*/ final ConceptDescriptor myConceptSearch = createDescriptorForSearch();
  /*package*/ final ConceptDescriptor myConceptTemplate = createDescriptorForTemplate();
  /*package*/ final ConceptDescriptor myConceptTemplateElement = createDescriptorForTemplateElement();
  /*package*/ final EnumerationDescriptor myEnumerationIcons = new EnumerationDescriptor_Icons();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptApp, myConceptButton, myConceptClickable, myConceptConfiguration, myConceptGrid, myConceptIcon, myConceptNavBar, myConceptPage, myConceptRoute, myConceptSearch, myConceptTemplate, myConceptTemplateElement);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.App:
        return myConceptApp;
      case LanguageConceptSwitch.Button:
        return myConceptButton;
      case LanguageConceptSwitch.Clickable:
        return myConceptClickable;
      case LanguageConceptSwitch.Configuration:
        return myConceptConfiguration;
      case LanguageConceptSwitch.Grid:
        return myConceptGrid;
      case LanguageConceptSwitch.Icon:
        return myConceptIcon;
      case LanguageConceptSwitch.NavBar:
        return myConceptNavBar;
      case LanguageConceptSwitch.Page:
        return myConceptPage;
      case LanguageConceptSwitch.Route:
        return myConceptRoute;
      case LanguageConceptSwitch.Search:
        return myConceptSearch;
      case LanguageConceptSwitch.Template:
        return myConceptTemplate;
      case LanguageConceptSwitch.TemplateElement:
        return myConceptTemplateElement;
      default:
        return null;
    }
  }

  @Override
  public Collection<DataTypeDescriptor> getDataTypeDescriptors() {
    return Arrays.asList(myEnumerationIcons);
  }

  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForApp() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("WebGen", "App", 0x524c482858c411cL, 0x9a4ee783c820e868L, 0x4b0f3085b2fa290cL);
    b.class_(false, false, true);
    b.origin("r:b4f30641-7f1b-428b-b3d8-bf4ba03b50c5(WebGen.structure)/5408595028286777612");
    b.version(2);
    b.aggregate("templates", 0x4b0f3085b2fa290dL).target(0x524c482858c411cL, 0x9a4ee783c820e868L, 0x4b0f3085b2f914c9L).optional(true).ordered(true).multiple(true).origin("5408595028286777613").done();
    b.aggregate("pages", 0x2f6f0a41e01b9383L).target(0x524c482858c411cL, 0x9a4ee783c820e868L, 0x2f6f0a41e01b9380L).optional(false).ordered(true).multiple(true).origin("3417961920246551427").done();
    b.aggregate("theme", 0x2f6f0a41e01bdc8cL).target(0x524c482858c411cL, 0x9a4ee783c820e868L, 0x4b0f3085b2fa290fL).optional(false).ordered(true).multiple(false).origin("3417961920246570124").done();
    b.alias("app");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForButton() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("WebGen", "Button", 0x524c482858c411cL, 0x9a4ee783c820e868L, 0x4b0f3085b2f89485L);
    b.class_(false, false, false);
    b.super_("WebGen.structure.Clickable", 0x524c482858c411cL, 0x9a4ee783c820e868L, 0x4b0f3085b2f8d903L);
    b.origin("r:b4f30641-7f1b-428b-b3d8-bf4ba03b50c5(WebGen.structure)/5408595028286674053");
    b.version(2);
    b.property("text", 0x4b0f3085b2f89486L).type(PrimitiveTypeId.STRING).origin("5408595028286674054").done();
    b.alias("button");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForClickable() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("WebGen", "Clickable", 0x524c482858c411cL, 0x9a4ee783c820e868L, 0x4b0f3085b2f8d903L);
    b.class_(false, true, false);
    b.super_("WebGen.structure.TemplateElement", 0x524c482858c411cL, 0x9a4ee783c820e868L, 0x4b0f3085b2f914c3L);
    b.origin("r:b4f30641-7f1b-428b-b3d8-bf4ba03b50c5(WebGen.structure)/5408595028286691587");
    b.version(2);
    b.property("functionName", 0x4b0f3085b2f8d906L).type(PrimitiveTypeId.STRING).origin("5408595028286691590").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForConfiguration() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("WebGen", "Configuration", 0x524c482858c411cL, 0x9a4ee783c820e868L, 0x4b0f3085b2fa290fL);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:b4f30641-7f1b-428b-b3d8-bf4ba03b50c5(WebGen.structure)/5408595028286777615");
    b.version(2);
    b.property("json", 0x4b0f3085b2fa2910L).type(PrimitiveTypeId.STRING).origin("5408595028286777616").done();
    b.alias("configuration");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForGrid() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("WebGen", "Grid", 0x524c482858c411cL, 0x9a4ee783c820e868L, 0x4b0f3085b2f914c6L);
    b.class_(false, false, false);
    b.super_("WebGen.structure.TemplateElement", 0x524c482858c411cL, 0x9a4ee783c820e868L, 0x4b0f3085b2f914c3L);
    b.origin("r:b4f30641-7f1b-428b-b3d8-bf4ba03b50c5(WebGen.structure)/5408595028286706886");
    b.version(2);
    b.aggregate("templateElements", 0x4b0f3085b2f914c7L).target(0x524c482858c411cL, 0x9a4ee783c820e868L, 0x4b0f3085b2f914c3L).optional(true).ordered(true).multiple(true).origin("5408595028286706887").done();
    b.alias("grid");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForIcon() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("WebGen", "Icon", 0x524c482858c411cL, 0x9a4ee783c820e868L, 0x4b0f3085b2f7dad9L);
    b.class_(false, false, false);
    b.super_("WebGen.structure.Clickable", 0x524c482858c411cL, 0x9a4ee783c820e868L, 0x4b0f3085b2f8d903L);
    b.origin("r:b4f30641-7f1b-428b-b3d8-bf4ba03b50c5(WebGen.structure)/5408595028286626521");
    b.version(2);
    b.property("size", 0x4b0f3085b2f7dadeL).type(PrimitiveTypeId.STRING).origin("5408595028286626526").done();
    b.property("color", 0x4b0f3085b2f7dae0L).type(PrimitiveTypeId.STRING).origin("5408595028286626528").done();
    b.associate("icon", 0x4b0f3085b2f7dadcL).target(0x524c482858c411cL, 0x9a4ee783c820e868L, 0x4b0f3085b2f7dad9L).optional(true).origin("5408595028286626524").done();
    b.alias("icon");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForNavBar() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("WebGen", "NavBar", 0x524c482858c411cL, 0x9a4ee783c820e868L, 0x2f6f0a41e01b4f85L);
    b.class_(false, false, false);
    b.origin("r:b4f30641-7f1b-428b-b3d8-bf4ba03b50c5(WebGen.structure)/3417961920246534021");
    b.version(2);
    b.associate("template", 0x2f6f0a41e01b4f86L).target(0x524c482858c411cL, 0x9a4ee783c820e868L, 0x4b0f3085b2f914c9L).optional(false).origin("3417961920246534022").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForPage() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("WebGen", "Page", 0x524c482858c411cL, 0x9a4ee783c820e868L, 0x2f6f0a41e01b9380L);
    b.class_(false, true, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:b4f30641-7f1b-428b-b3d8-bf4ba03b50c5(WebGen.structure)/3417961920246551424");
    b.version(2);
    b.associate("template", 0x2f6f0a41e01ce13cL).target(0x524c482858c411cL, 0x9a4ee783c820e868L, 0x4b0f3085b2f914c9L).optional(false).origin("3417961920246636860").done();
    b.associate("route", 0x2f6f0a41e01d0876L).target(0x524c482858c411cL, 0x9a4ee783c820e868L, 0x2f6f0a41e01ce203L).optional(false).origin("3417961920246646902").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForRoute() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("WebGen", "Route", 0x524c482858c411cL, 0x9a4ee783c820e868L, 0x2f6f0a41e01ce203L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:b4f30641-7f1b-428b-b3d8-bf4ba03b50c5(WebGen.structure)/3417961920246637059");
    b.version(2);
    b.property("route", 0x2f6f0a41e01ce40fL).type(PrimitiveTypeId.STRING).origin("3417961920246637583").done();
    b.property("isHome", 0x2f6f0a41e01b9386L).type(PrimitiveTypeId.BOOLEAN).origin("3417961920246551430").done();
    b.associate("page", 0x2f6f0a41e01cfaf0L).target(0x524c482858c411cL, 0x9a4ee783c820e868L, 0x2f6f0a41e01b9380L).optional(false).origin("3417961920246643440").done();
    b.alias("route");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForSearch() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("WebGen", "Search", 0x524c482858c411cL, 0x9a4ee783c820e868L, 0x4b0f3085b2f8f7a6L);
    b.class_(false, false, false);
    b.super_("WebGen.structure.TemplateElement", 0x524c482858c411cL, 0x9a4ee783c820e868L, 0x4b0f3085b2f914c3L);
    b.origin("r:b4f30641-7f1b-428b-b3d8-bf4ba03b50c5(WebGen.structure)/5408595028286699430");
    b.version(2);
    b.property("functionName", 0x4b0f3085b2f8f7a7L).type(PrimitiveTypeId.STRING).origin("5408595028286699431").done();
    b.alias("searchBar");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForTemplate() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("WebGen", "Template", 0x524c482858c411cL, 0x9a4ee783c820e868L, 0x4b0f3085b2f914c9L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:b4f30641-7f1b-428b-b3d8-bf4ba03b50c5(WebGen.structure)/5408595028286706889");
    b.version(2);
    b.aggregate("templateElements", 0x4b0f3085b2f914ccL).target(0x524c482858c411cL, 0x9a4ee783c820e868L, 0x4b0f3085b2f914c3L).optional(false).ordered(true).multiple(true).origin("5408595028286706892").done();
    b.alias("template");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForTemplateElement() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("WebGen", "TemplateElement", 0x524c482858c411cL, 0x9a4ee783c820e868L, 0x4b0f3085b2f914c3L);
    b.class_(false, true, false);
    b.origin("r:b4f30641-7f1b-428b-b3d8-bf4ba03b50c5(WebGen.structure)/5408595028286706883");
    b.version(2);
    return b.create();
  }
}
